### ISSUE TITLE
Function build_fr_combined_network

### ISSUE THREAD

**Issue by gillesvtsilvano** [PacktPublishing/Generative-Adversarial-Networks-Projects#12]
Hi! I am going through your book. Very good reading btw.

I was trying to implement Age-cGAN in Chapter 03 and I couldn't find where the function `build_fr_combined_network` is called on the code.

Do I missed something? Thanks in advance.

**Comment by kailashahirwar** [comment]
@gillesvtsilvano Yes. I did not use build_fr_combined_network() function. I used build_fr_model() function. You can ignore that.
