### ISSUE TITLE
Upsampling vs Deconv?

### ISSUE THREAD

**Issue by icompute386** [PacktPublishing/Generative-Adversarial-Networks-Projects#2]
Chapters 2 and 3 use two different methods of upscaling; from a vector to a volume/image.

Why was Deconv() used in 3D-GAN, and UpSampling/Conv used for face generation?

Thanks,
Chris

**Comment by kailashahirwar** [comment]
Both are the same operations. You can use Deconv() or Upsampling/Conv, anyone if fine.
