### ISSUE TITLE
3D Gan Generates always a cube

### ISSUE THREAD

**Issue by alexsteinerr** [PacktPublishing/Generative-Adversarial-Networks-Projects#204]
After training the gan it always generates a cube as the g loss increases 
![img_85_0_0](https://user-images.githubusercontent.com/65250433/220321326-ea751d57-9a80-4ef1-ae29-5936bcc77023.png)

**Comment by rajat-packt** [comment]
Hey @kailashahirwar, would you be able to help out our reader with this query?

**Comment by kailashahirwar** [comment]
Hi Rajat, please share your model architecture and various hyperparameters you are using for the training.

**Comment by rajat-packt** [comment]
Hey @AlexSteiner30, please share these details with Kailash, he'll definitely be able to help you with your queries.

**Comment by HoqueMahmudul** [comment]
Good Afternoon @rajat-packt, I am facing similar issue with GAN always generating Cube. Shall I share my details here?

**Comment by alexsteinerr** [comment]
> Good Afternoon @rajat-packt, I am facing similar issue with GAN always generating Cube. Shall I share my details here?

Hey @HoqueMahmudul can you provide more details in order for me to help you and give you some recommendations? Anyways I would recommend you to use a GAN that learns on faces and vertices as 3D reconstruction from point clouds is a real hard task and most of the algorithms out there usually dont fit or work for every use case.
