### ISSUE TITLE
Chap06 python3 run.py

### ISSUE THREAD

**Issue by artificialnouveau** [PacktPublishing/Generative-Adversarial-Networks-Projects#29]
There is no run.py in the Chap06 repository. Is there a missing file or should we run stage1.py and stage2.py separately?

**Comment by kailashahirwar** [comment]
@artificalnouveau Yes, you have to run them separately. StackGAN is divided into two stages. Start with stage1.py and after the training completes for stage-I, start training for stage-II.

**Comment by gaurav-packt** [comment]
Thanks for the feedback; with this closing the issue.
