### ISSUE TITLE
3d model not generated

### ISSUE THREAD

**Issue by sushantmakadia** [PacktPublishing/Generative-Adversarial-Networks-Projects#31]
in chapter 2
![Capture](https://user-images.githubusercontent.com/37360314/68651195-e5d7cd00-054c-11ea-9500-c3b382fe5d96.JPG)
i run this program at 10,20,100,200 eppoch ,but cant get results.

**Comment by kailashahirwar** [comment]
Hey, 

This is a very common problem.

I will have a look and get back to you.

**Comment by sushantmakadia** [comment]
Ok thanks . Pls do as soon as possible.

**Comment by 19akhilesh98** [comment]
I have the same issue please give a solution as soon as possible.

**Comment by NilishaGupta** [comment]
I also have the same issue.

**Comment by jimmywang92** [comment]
i have the same issue, please kindly help thank you

**Comment by divakrishnam** [comment]
I also have the same issue, please give a solution as soon as possible.

**Comment by kailashahirwar** [comment]
Hey guys,

Try your networks with different hyperparameters. 

Hopefully, you will get your results.

Due to my busy schedule, I am not able to work on it again. Working on two startups is difficult.

**Comment by Adelina1237** [comment]
ValueError: 'a' cannot be empty unless no samples are taken
Why?(
not compiled
