### ISSUE TITLE
I can't download 3D shapeNetsCode.zip

### ISSUE THREAD

**Issue by tigon7476** [PacktPublishing/Generative-Adversarial-Networks-Projects#32]
I can't download 3D shapeNetsCode.zip from http://3dshapenets.cs.princeton.edu/3DShapeNetsCode.zip

**Comment by kailashahirwar** [comment]
Why? I can easily download the zip file. Check if you need to get permissions from the authors.

**Comment by tigon7476** [comment]
I'm sorry, I was not case sensitive TT
