### ISSUE TITLE
codes in chapter4 dosen't work

### ISSUE THREAD

**Issue by dnvs** [PacktPublishing/Generative-Adversarial-Networks-Projects#47]
it seems it's using a wiki dataset(.mat file) , but the codes in the book are  using just a directory.

**Comment by kailashahirwar** [comment]
Hey

**Comment by dnvs** [comment]
hi, i'v using a venv and installed dependencies from requirements.txt. i found the codes is slight different with the book,  stuck in this chapter, please help.

**Comment by kailashahirwar** [comment]
Sure, I will have a look.
