### ISSUE TITLE
chapter 8, the dataset

### ISSUE THREAD

**Issue by qsz746** [PacktPublishing/Generative-Adversarial-Networks-Projects#48]
I read the book chapter 8 for the project of the facade, according to the book, the file structure of the downloaded dataset is as follows: training(facades, images), validation(facades, images), testing(facades, images).  But the dataset I downloaded from the link provided, there is no h5. files in the dataset, and there is no subfiles (facades, images) in my training, validation, testing files. 
Is that possible that the dataset link provided in the book doesn't match the code provided?

**Comment by kailashahirwar** [comment]
Hey, the owners of the dataset might have changed the file structure. Packt or I do not own the dataset. If it not working for you, you should download a different dataset.
