### ISSUE TITLE
Issue after 1 Epoch SRGAN

### ISSUE THREAD

**Issue by lpassarella** [PacktPublishing/Generative-Adversarial-Networks-Projects#53]
I am trying to train a SRGAN and after the first epoch I get the following error:

FailedPreconditionError:  Error while reading resource variable _AnonymousVar1184 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/_AnonymousVar1184/N10tensorflow3VarE does not exist.
	 [[node mul_965/ReadVariableOp (defined at /global/homes/l/lpass/.conda/envs/myenv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_59848]

Function call stack:
keras_scratch_graph

It happens after calling:
d_loss_real = discriminator.train_on_batch(high_resolution_images, real_labels)

**Comment by kailashahirwar** [comment]
Did you install dependencies as given in the requirements.txt file?

**Comment by lpassarella** [comment]
Yes, although I cannot install tensorboard 1.12.2 because it isn't compatible with tensorflow 1.12.0 so I am using tensorboard 1.14.0

**Comment by kailashahirwar** [comment]
Are you using Tensorflow keras or Keras?

**Comment by kailashahirwar** [comment]
@lpassarella Did you verify your dependencies?

**Comment by sonam-packt** [comment]
@lpassarella Seems like your issue has been resolved, please reopen if the issue still persists.
