### ISSUE TITLE
Chapter 04 activation function for generator.

### ISSUE THREAD

**Issue by MankaranSingh** [PacktPublishing/Generative-Adversarial-Networks-Projects#6]
In chapter 04, Anime character generation using DCGAN, in the line by line explanation of the generator, 'tanh' activation function is used, but in the get_generator() method, LeakyRelu(0.2) is used, and in the github code, Relu is used.  

Now the question is, which activation function actually to use !!??

**Comment by kailashahirwar** [comment]
@MankaranSingh I have experimented with many activation functions. I tried tanh and LeakyRelu. You can use any activation function based on your intuition. You need to experiment more.
