### ISSUE TITLE
Absurd results!!!

### ISSUE THREAD

**Issue by shivanikush** [PacktPublishing/Generative-Adversarial-Networks-Projects#7]
I was running your code of Age CGAN and after running the code for 230 epochs the results are not improving, how come you got the results, so clearly???The results needed to be imporved through every epoch, but it is happening just the opposite of it.

![img_230_1](https://user-images.githubusercontent.com/30427045/61266825-2ef05e00-a7b3-11e9-9100-ae227cc66259.png)

**Comment by kailashahirwar** [comment]
You need to train it more or you can try different hyperparameters.

**Comment by kailashahirwar** [comment]
@shivanikush Most of the times it depends on weight initialization as well. You need to experiment more.
If possible share your parameters here with me.

**Comment by kailashahirwar** [comment]
Hey @shivanikush Can you update me with your results?
