### ISSUE TITLE
Getting Attribute error " 'int' object has no attribute 'shape' - Chapter 03

### ISSUE THREAD

**Issue by bineetha1995** [PacktPublishing/Generative-Adversarial-Networks-Projects#70]
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fa9341bd820> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_train_function.<locals>.train_function at 0x7fa8c8b05af0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
d_loss:1.9753593802452087
Traceback (most recent call last):

  File "/home/user/FaceAging/age_gan.py", line 406, in <module>
    g_loss = adversarial_model.train_on_batch([z_noise2, random_labels], [1] * batch_size)

  File "/home/user/anaconda3/envs/GAN/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1723, in train_on_batch
    iterator = data_adapter.single_batch_iterator(self.distribute_strategy, x,

  File "/home/user/anaconda3/envs/GAN/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1513, in single_batch_iterator
    _check_data_cardinality(data)

  File "/home/user/anaconda3/envs/GAN/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1522, in _check_data_cardinality
    num_samples = set(int(i.shape[0]) for i in nest.flatten(data))

  File "/home/user/anaconda3/envs/GAN/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1522, in <genexpr>
    num_samples = set(int(i.shape[0]) for i in nest.flatten(data))

**AttributeError: 'int' object has no attribute 'shape'**

**Comment by kailashmatelabs** [comment]
Hey, Can you share the full code here?. It looks like you are passing the wrong values.

**Comment by m-ali-awan** [comment]
Please, do not close the issue, as it is not solved.
And please help out, as I am also facing this issue...

Thanks...

**Comment by shruthis-shetty** [comment]
Hi @m-ali-awan 
The issue has been reopened.
Please feel free to contact me if you're still facing any issues.

**Comment by m-ali-awan** [comment]
Thanks @shruthis-shetty 
Yes, I am facing the same issue........

**Comment by shruthis-shetty** [comment]
Hello @m-ali-awan 
Please give us some time and we'll get it solved asap.

**Comment by shruthis-shetty** [comment]
Hi @m-ali-awan,
@kailashmatelabs is the author of this title and he's trying to solve this issue but as @bineetha1995 was not active he didn't shared the entire code related to this issue.
If you could share the code where exactly you're getting the error that'll be helpful for the author to get more clarity on the issue. 
Thanks

**Comment by m-ali-awan** [comment]
`  for epoch in range(epochs):
      print("Epoch:{}".format(epoch))

      gen_losses = []
      dis_losses = []

      number_of_batches = int(len(loaded_images) / batch_size)
      print("Number of batches:", number_of_batches)
      for index in range(number_of_batches):
          print("Batch:{}".format(index + 1))

          images_batch = loaded_images[index * batch_size:(index + 1) * batch_size]
          images_batch = images_batch / 127.5 - 1.0
          images_batch = images_batch.astype(np.float32)

          y_batch = y[index * batch_size:(index + 1) * batch_size]
          z_noise = np.random.normal(0, 1, size=(batch_size, z_shape))

          """
          Train the discriminator network
          """

          # Generate fake images
          initial_recon_images = generator.predict_on_batch([z_noise, y_batch])

          d_loss_real = discriminator.train_on_batch([images_batch, y_batch], real_labels)
          d_loss_fake = discriminator.train_on_batch([initial_recon_images, y_batch], fake_labels)

          d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)
          print("d_loss:{}".format(d_loss))

          """
          Train the generator network
          """

          z_noise2 = np.random.normal(0, 1, size=(batch_size, z_shape))
          random_labels = np.random.randint(0, 6, batch_size).reshape(-1, 1)
          random_labels = to_categorical(random_labels, 6)

          g_loss = adversarial_model.train_on_batch([z_noise2, random_labels], [1] * batch_size)

          print("g_loss:{}".format(g_loss))

          gen_losses.append(g_loss)
          dis_losses.append(d_loss)

      # Write losses to Tensorboard
      write_log(tensorboard, 'g_loss', np.mean(gen_losses), epoch)
      write_log(tensorboard, 'd_loss', np.mean(dis_losses), epoch)

      """
      Generate images after every 10th epoch
      """
      if epoch % 10 == 0:
          images_batch = loaded_images[0:batch_size]
          images_batch = images_batch / 127.5 - 1.0
          images_batch = images_batch.astype(np.float32)

          y_batch = y[0:batch_size]
          z_noise = np.random.normal(0, 1, size=(batch_size, z_shape))

          gen_images = generator.predict_on_batch([z_noise, y_batch])

          for i, img in enumerate(gen_images[:5]):
              save_rgb_img(img, path="results/img_{}_{}.png".format(epoch, i))

  # Save networks
  try:
      generator.save_weights("generator.h5")
      discriminator.save_weights("discriminator.h5")
  except Exception as e:
      print("Error:", e)`


`Epoch:0
Number of batches: 15
Batch:1
d_loss:1.4583944082260132
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-c04fb47b861a> in <module>()
     38         random_labels = to_categorical(random_labels, 6)
     39 
---> 40         g_loss = adversarial_model.train_on_batch([z_noise2, random_labels], [1] * batch_size)
     41 
     42         print("g_loss:{}".format(g_loss))

3 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/data_adapter.py in <genexpr>(.0)
   1520 
   1521 def _check_data_cardinality(data):
-> 1522   num_samples = set(int(i.shape[0]) for i in nest.flatten(data))
   1523   if len(num_samples) > 1:
   1524     msg = "Data cardinality is ambiguous:\n"

AttributeError: 'int' object has no attribute 'shape'`

**Comment by bineetha1995** [comment]
[Age-Gan.zip](https://github.com/PacktPublishing/Generative-Adversarial-Networks-Projects/files/6328899/Age-Gan.zip)



d_loss:1.4829263091087341
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-779f9d4086f5> in <module>
    404                 random_labels = to_categorical(random_labels, 6)
    405 
--> 406                 g_loss = adversarial_model.train_on_batch([z_noise2, random_labels], [1] * batch_size)
    407 
    408                 print("g_loss:{}".format(g_loss))

D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\keras\engine\training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics, return_dict)
   1693                                                     class_weight)
   1694       train_function = self.make_train_function()
-> 1695       logs = train_function(iterator)
   1696 
   1697     if reset_metrics:

D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\eager\def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\eager\def_function.py in _call(self, *args, **kwds)
    821       # This is the first call of __call__, so we have to initialize.
    822       initializers = []
--> 823       self._initialize(args, kwds, add_initializers_to=initializers)
    824     finally:
    825       # At this point we know that the initialization is complete (or less

D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\eager\def_function.py in _initialize(self, args, kwds, add_initializers_to)
    695     self._concrete_stateful_fn = (
    696         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 697             *args, **kwds))
    698 
    699     def invalid_creator_scope(*unused_args, **unused_kwds):

D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\eager\function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2853       args, kwargs = None, None
   2854     with self._lock:
-> 2855       graph_function, _, _ = self._maybe_define_function(args, kwargs)
   2856     return graph_function
   2857 

D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\eager\function.py in _maybe_define_function(self, args, kwargs)
   3211 
   3212       self._function_cache.missed.add(call_context_key)
-> 3213       graph_function = self._create_graph_function(args, kwargs)
   3214       self._function_cache.primary[cache_key] = graph_function
   3215       return graph_function, args, kwargs

D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\eager\function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3073             arg_names=arg_names,
   3074             override_flat_arg_shapes=override_flat_arg_shapes,
-> 3075             capture_by_value=self._capture_by_value),
   3076         self._function_attributes,
   3077         function_spec=self.function_spec,

D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\framework\func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    984         _, original_func = tf_decorator.unwrap(python_func)
    985 
--> 986       func_outputs = python_func(*func_args, **func_kwargs)
    987 
    988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\eager\def_function.py in wrapped_fn(*args, **kwds)
    598         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    599         # the function a weak reference to itself to avoid a reference cycle.
--> 600         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    601     weak_wrapped_fn = weakref.ref(wrapped_fn)
    602 

D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\framework\func_graph.py in wrapper(*args, **kwargs)
    971           except Exception as e:  # pylint:disable=broad-except
    972             if hasattr(e, "ag_error_metadata"):
--> 973               raise e.ag_error_metadata.to_exception(e)
    974             else:
    975               raise

ValueError: in user code:

    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\keras\engine\training.py:749 train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:204 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\keras\losses.py:149 __call__
        losses = ag_call(y_true, y_pred)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\keras\losses.py:253 call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\keras\losses.py:1605 binary_crossentropy
        K.binary_crossentropy(y_true, y_pred, from_logits=from_logits), axis=-1)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\keras\backend.py:4823 binary_crossentropy
        return nn.sigmoid_cross_entropy_with_logits(labels=target, logits=output)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    D:\Anaconda3\envs\gan\lib\site-packages\tensorflow\python\ops\nn_impl.py:174 sigmoid_cross_entropy_with_logits
        (logits.get_shape(), labels.get_shape()))

    ValueError: logits and labels must have the same shape ((2, 1) vs ())

**Comment by shruthis-shetty** [comment]
Hi @kailashmatelabs ,
@bineetha1995 has shared the code. Please check with this.

**Comment by bineetha1995** [comment]
d_loss: 1.6546609997749329
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-921166889336> in <module>()
    118         random_labels = to_categorical(random_labels, 6)
    119 
--> 120         g_loss = adversarial_model.train_on_batch([z_noise2, random_labels], [1] * batch_size)
    121 
    122         print("g_loss: {}".format(g_loss))

3 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/data_adapter.py in <genexpr>(.0)
   1520 
   1521 def _check_data_cardinality(data):
-> 1522   num_samples = set(int(i.shape[0]) for i in nest.flatten(data))
   1523   if len(num_samples) > 1:
   1524     msg = "Data cardinality is ambiguous:\n"

AttributeError: 'int' object has no attribute 'shape'

**Comment by leminhds** [comment]
Hi, I am facing the same issue... has anyone found the solution yet?

**Comment by leminhds** [comment]
I found the solution. From TF 2.2.0 Model doesn't support list anymore. Therefore, we need to transform [1] * batch_size into an array
`np.asarray([1] * batch_size)`
