### ISSUE TITLE
ValueError: 'a' cannot be empty unless no samples are taken (chap07)

### ISSUE THREAD

**Issue by 438-gm-24** [PacktPublishing/Generative-Adversarial-Networks-Projects#78]
Hello, 
I work with a recent version of tensorflow 2.4.1. when i run the code I feel like than then can't load data that were in data folder /data/monet2photo. So I have error like :
 ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "run.py", line 324, in <module>
    batchA, batchB = load_test_batch(data_dir=data_dir, batch_size=2)
  File "run.py", line 144, in load_test_batch
    imagesA = np.random.choice(imagesA, batch_size)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

**Comment by kailashmatelabs** [comment]
Use tensorflow==1.12.0
