### ISSUE TITLE
Discriminator Generator loss graph

### ISSUE THREAD

**Issue by Guidosalimbeni** [PacktPublishing/Generative-Adversarial-Networks-Projects#8]
Just going through your book. Great reading.
It is not clear to me how to read the graph for a DCGAN. I have implemented your code and the model is still learning. Can you tell me if this trend is good.? please see picture
[https://www.screencast.com/t/IgGEdgh8e9j](url)

In the book the graph is similar to mine but I thought the Generator Loss should decreasing ?

**Comment by kailashahirwar** [comment]
@Guidosalimbeni Hey. Really sorry for the late response. I have been busy with my startup. Can you share the graph again?. I would love to help you.
